CREATE TABLE USER(
 `id` INT(10) NOT NULL AUTO_INCREMENT,
 `name` VARCHAR(10) NOT NULL ,
 `gender` VARCHAR(1) NOT NULL,
 `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
 `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (`id`) USING BTREE
) DEFAULT CHARSET=utf8;