spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb01?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=FALSE
    username: root
    password: root
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  type-aliases-package: com.springboot.schedule.demo.entity